// Generated from the translators' JSON (en + 18) by scratchpad i18n/merge.py. Do not edit by hand.
export const STRINGS = {
 "en": {
  "page_title": "Spriteer — Three frames. Every game.",
  "page_title_c": "A Spriteer challenge",
  "get_app": "Get the app",
  "challenge_default": "A challenge",
  "challenge_lede": "Make your own fighter below — four dots — then stomp it 3 times in 30 seconds.",
  "challenge_name": "{name} challenges you",
  "h1": "Three frames. Every game.",
  "lede": "Every character is Idle · Walk · Die. Fill the four dots on Walk and watch it walk.",
  "idle": "Idle",
  "walk": "Walk",
  "die": "Die",
  "live": "Live",
  "goal_tap": "Tap the blinking dots on Walk.",
  "goal_walks": "It walks! The duel starts in a moment…",
  "goal_ready": "Press Play when ready.",
  "play": "Play ▶",
  "another": "Another sketch",
  "name_label": "Name",
  "duel_title": "Stomp duel",
  "rival_line": "Stomp the rival 3 times in 30 seconds",
  "close": "Close",
  "move_left": "Move left",
  "move_right": "Move right",
  "jump": "JUMP",
  "keys_line": "← → / A D  Move · Space ↑ W  Jump · Esc  Close · Pad: A Jump, B Close",
  "hud_you": "YOU {n}",
  "hud_rival": "{n} RIVAL",
  "hud_rule": "Stomp 3 times · 30s",
  "hud_go": "GO",
  "result_draw": "A draw, {a}–{b}.",
  "result_won": "You won {a}–{b}!",
  "result_lost": "The rival won {b}–{a}.",
  "moved_in": "{name} moved into your house · {n}",
  "guest_stays": "{name} stays as your guest.",
  "challenge_friend": "Challenge a friend",
  "rematch": "Rematch",
  "draw_another": "Draw another",
  "your_house": "Your house",
  "house_lede": "Everyone you finish moves in. Pythoneer's Pys, pets and fish live here too.",
  "house_empty": "No one lives here yet — fill four dots above.",
  "residents_one": "{n} resident",
  "residents_other": "{n} residents",
  "guests_one": "{n} guest",
  "guests_other": "{n} guests",
  "py_counts": "Pys {a}/{b} · Pets {c}/{d} · Fish {e}/{f}",
  "door_sp": "The shelf, the tank and the pets are empty until you bring them from Pythoneer. Your house goes with you.",
  "visit": "Visit",
  "take_to_app": "Take them to the app",
  "save_png": "Save house as Skin PNG",
  "tag_resident": "Resident",
  "tag_guest": "Guest",
  "btn_duel": "Duel",
  "btn_challenge": "Challenge",
  "btn_open_app": "Open in app",
  "share_text": "{name} challenges you. Stomp it 3 times in 30 seconds.",
  "link_copied": "Link copied",
  "copy_prompt": "Copy this link",
  "bad_link": "This link could not be read. Ask for a fresh one.",
  "privacy": "Privacy",
  "privacy_title": "Privacy",
  "privacy_p1": "What you draw and your house stay in this browser. Nothing is uploaded.",
  "privacy_p2": "A challenge link carries your character after the #. That part of a link never reaches our server; whoever you send it to can see the character.",
  "privacy_p3": "We count anonymous page events (for example \"a duel started\") with a random number made fresh for each visit. No cookies, no accounts, no IP addresses kept.",
  "privacy_p4": "The Spriteer app has its own policy in the App Store listing. Questions: {email}.",
  "not_here": "Not here.",
  "draw_instead": "Draw a character instead →"
 },
 "ar": {
  "page_title": "Spriteer — ثلاثة إطارات. كل لعبة.",
  "page_title_c": "تحدٍّ من Spriteer",
  "get_app": "احصل على التطبيق",
  "challenge_default": "تحدٍّ",
  "challenge_lede": "اصنع مقاتلك الخاص بالأسفل — أربع نقاط — ثم اقفز على رأس الخصم 3 مرات في 30 ثانية.",
  "challenge_name": "{name} يتحداك",
  "h1": "ثلاثة إطارات. كل لعبة.",
  "lede": "كل شخصية لها ساكن · مشي · الموت. املأ النقاط الأربع في مشي وشاهدها تمشي.",
  "idle": "ساكن",
  "walk": "مشي",
  "die": "الموت",
  "live": "مباشر",
  "goal_tap": "اضغط على النقاط الوامضة في مشي.",
  "goal_walks": "إنها تمشي! تبدأ المبارزة بعد لحظة…",
  "goal_ready": "اضغط العب عندما تكون جاهزًا.",
  "play": "العب ▶",
  "another": "رسمة أخرى",
  "name_label": "الاسم",
  "duel_title": "مبارزة القفز",
  "rival_line": "اقفز على رأس الخصم 3 مرات في 30 ثانية",
  "close": "إغلاق",
  "move_left": "تحرك يسارًا",
  "move_right": "تحرك يمينًا",
  "jump": "قفز",
  "keys_line": "← → / A D  تحرك · Space ↑ W  قفز · Esc  إغلاق · ذراع التحكم: A قفز، B إغلاق",
  "hud_you": "أنت {n}",
  "hud_rival": "{n} الخصم",
  "hud_rule": "اقفز 3 مرات · 30 ث",
  "hud_go": "انطلق",
  "result_draw": "تعادل، {a}–{b}.",
  "result_won": "فزت {a}–{b}!",
  "result_lost": "فاز الخصم {b}–{a}.",
  "moved_in": "{name} انتقل إلى منزلك · {n}",
  "guest_stays": "{name} يبقى ضيفًا عندك.",
  "challenge_friend": "تحدَّ صديقًا",
  "rematch": "مباراة جديدة",
  "draw_another": "ارسم شخصية أخرى",
  "your_house": "منزلك",
  "house_lede": "كل من تُكمله ينتقل إلى هنا. باي والحيوانات الأليفة والأسماك من Pythoneer تعيش هنا أيضًا.",
  "house_empty": "لا أحد يسكن هنا بعد — املأ أربع نقاط في الأعلى.",
  "residents_one": "{n} ساكن",
  "residents_other": "{n} من السكان",
  "guests_one": "{n} ضيف",
  "guests_other": "{n} من الضيوف",
  "py_counts": "باي {a}/{b} · حيوانات أليفة {c}/{d} · أسماك {e}/{f}",
  "door_sp": "الرف والحوض والحيوانات الأليفة فارغة حتى تجلبها من Pythoneer. منزلك يرافقك.",
  "visit": "زيارة",
  "take_to_app": "خذهم إلى التطبيق",
  "save_png": "احفظ المنزل كـ Skin PNG",
  "tag_resident": "ساكن",
  "tag_guest": "ضيف",
  "btn_duel": "مبارزة",
  "btn_challenge": "تحدٍّ",
  "btn_open_app": "افتح في التطبيق",
  "share_text": "{name} يتحداك. اقفز على رأسه 3 مرات في 30 ثانية.",
  "link_copied": "تم نسخ الرابط",
  "copy_prompt": "انسخ هذا الرابط",
  "bad_link": "تعذّرت قراءة هذا الرابط. اطلب رابطًا جديدًا.",
  "privacy": "الخصوصية",
  "privacy_title": "الخصوصية",
  "privacy_p1": "ما ترسمه ومنزلك يبقيان في هذا المتصفح. لا يُرفع أي شيء.",
  "privacy_p2": "رابط التحدي يحمل شخصيتك بعد علامة #. هذا الجزء من الرابط لا يصل أبدًا إلى خادمنا؛ ومن ترسله إليه يمكنه رؤية الشخصية.",
  "privacy_p3": "نحصي أحداث الصفحة دون تحديد الهوية (مثل \"بدأت مبارزة\") برقم عشوائي جديد لكل زيارة. لا ملفات تعريف ارتباط، ولا حسابات، ولا نحتفظ بعناوين IP.",
  "privacy_p4": "لتطبيق Spriteer سياسته الخاصة في صفحته على App Store. للأسئلة: {email}.",
  "not_here": "لا شيء هنا.",
  "draw_instead": "ارسم شخصية بدلًا من ذلك ←"
 },
 "de": {
  "page_title": "Spriteer — Drei Bilder. Jedes Spiel.",
  "page_title_c": "Eine Spriteer-Herausforderung",
  "get_app": "App laden",
  "challenge_default": "Eine Herausforderung",
  "challenge_lede": "Bau unten deinen eigenen Kämpfer — vier Punkte — und spring dann dem Gegner 3-mal in 30 Sekunden auf den Kopf.",
  "challenge_name": "{name} fordert dich heraus",
  "h1": "Drei Bilder. Jedes Spiel.",
  "lede": "Jede Figur ist Stehen · Gehen · Umfallen. Füll die vier Punkte bei Gehen und sieh zu, wie sie läuft.",
  "idle": "Stehen",
  "walk": "Gehen",
  "die": "Umfallen",
  "live": "Live",
  "goal_tap": "Tippe auf die blinkenden Punkte bei Gehen.",
  "goal_walks": "Sie läuft! Gleich beginnt das Duell …",
  "goal_ready": "Drück auf Spielen, wenn du bereit bist.",
  "play": "Spielen ▶",
  "another": "Neue Skizze",
  "name_label": "Name",
  "duel_title": "Sprung-Duell",
  "rival_line": "Spring dem Gegner 3-mal in 30 Sekunden auf den Kopf",
  "close": "Schließen",
  "move_left": "Nach links",
  "move_right": "Nach rechts",
  "jump": "SPRUNG",
  "keys_line": "← → / A D  Laufen · Space ↑ W  Springen · Esc  Schließen · Pad: A Springen, B Schließen",
  "hud_you": "DU {n}",
  "hud_rival": "{n} GEGNER",
  "hud_rule": "3-mal springen · 30 s",
  "hud_go": "LOS",
  "result_draw": "Unentschieden, {a}–{b}.",
  "result_won": "Gewonnen, {a}–{b}!",
  "result_lost": "Der Gegner gewinnt {b}–{a}.",
  "moved_in": "{name} ist in dein Haus eingezogen · {n}",
  "guest_stays": "{name} bleibt als Gast.",
  "challenge_friend": "Freund herausfordern",
  "rematch": "Revanche",
  "draw_another": "Noch eine Figur zeichnen",
  "your_house": "Dein Haus",
  "house_lede": "Alle, die du fertig machst, ziehen ein. Auch die Pys, Haustiere und Fische aus Pythoneer wohnen hier.",
  "house_empty": "Hier wohnt noch niemand — füll oben vier Punkte.",
  "residents_one": "{n} Bewohner",
  "residents_other": "{n} Bewohner",
  "guests_one": "{n} Gast",
  "guests_other": "{n} Gäste",
  "py_counts": "Pys {a}/{b} · Haustiere {c}/{d} · Fische {e}/{f}",
  "door_sp": "Regal, Aquarium und Haustiere bleiben leer, bis du sie aus Pythoneer mitbringst. Dein Haus kommt mit dir.",
  "visit": "Besuchen",
  "take_to_app": "In die App mitnehmen",
  "save_png": "Haus als Skin PNG sichern",
  "tag_resident": "Bewohner",
  "tag_guest": "Gast",
  "btn_duel": "Duell",
  "btn_challenge": "Herausfordern",
  "btn_open_app": "In der App öffnen",
  "share_text": "{name} fordert dich heraus. Spring ihr 3-mal in 30 Sekunden auf den Kopf.",
  "link_copied": "Link kopiert",
  "copy_prompt": "Diesen Link kopieren",
  "bad_link": "Dieser Link ließ sich nicht lesen. Bitte um einen neuen.",
  "privacy": "Datenschutz",
  "privacy_title": "Datenschutz",
  "privacy_p1": "Was du zeichnest und dein Haus bleiben in diesem Browser. Nichts wird hochgeladen.",
  "privacy_p2": "Ein Herausforderungslink trägt deine Figur hinter dem #. Dieser Teil eines Links erreicht nie unseren Server; wer den Link bekommt, kann die Figur sehen.",
  "privacy_p3": "Wir zählen anonyme Seitenereignisse (zum Beispiel „ein Duell hat begonnen“) mit einer Zufallszahl, die bei jedem Besuch neu entsteht. Keine Cookies, keine Konten, keine gespeicherten IP-Adressen.",
  "privacy_p4": "Die Spriteer-App hat ihre eigene Datenschutzerklärung im App Store. Fragen: {email}.",
  "not_here": "Hier ist nichts.",
  "draw_instead": "Zeichne lieber eine Figur →"
 },
 "es": {
  "page_title": "Spriteer — Tres fotogramas. Cada juego.",
  "page_title_c": "Un reto de Spriteer",
  "get_app": "Descargar la app",
  "challenge_default": "Un reto",
  "challenge_lede": "Crea tu propio luchador abajo — cuatro puntos — y luego pisa al rival 3 veces en 30 segundos.",
  "challenge_name": "{name} te reta",
  "h1": "Tres fotogramas. Cada juego.",
  "lede": "Cada personaje es Quieto · Caminar · Caer. Rellena los cuatro puntos de Caminar y míralo caminar.",
  "idle": "Quieto",
  "walk": "Caminar",
  "die": "Caer",
  "live": "En vivo",
  "goal_tap": "Toca los puntos que parpadean en Caminar.",
  "goal_walks": "¡Camina! El duelo empieza en un momento…",
  "goal_ready": "Pulsa Jugar cuando quieras.",
  "play": "Jugar ▶",
  "another": "Otro boceto",
  "name_label": "Nombre",
  "duel_title": "Duelo de pisotones",
  "rival_line": "Pisa al rival 3 veces en 30 segundos",
  "close": "Cerrar",
  "move_left": "Mover a la izquierda",
  "move_right": "Mover a la derecha",
  "jump": "SALTAR",
  "keys_line": "← → / A D  Mover · Space ↑ W  Saltar · Esc  Cerrar · Mando: A Saltar, B Cerrar",
  "hud_you": "TÚ {n}",
  "hud_rival": "{n} RIVAL",
  "hud_rule": "Pisa 3 veces · 30 s",
  "hud_go": "¡YA!",
  "result_draw": "Empate, {a}–{b}.",
  "result_won": "¡Ganaste {a}–{b}!",
  "result_lost": "Ganó el rival {b}–{a}.",
  "moved_in": "{name} se mudó a tu casa · {n}",
  "guest_stays": "{name} se queda como invitado.",
  "challenge_friend": "Reta a un amigo",
  "rematch": "Revancha",
  "draw_another": "Dibujar otro",
  "your_house": "Tu casa",
  "house_lede": "Todos los que terminas se mudan aquí. Los Pys, mascotas y peces de Pythoneer también viven aquí.",
  "house_empty": "Aún no vive nadie aquí — rellena cuatro puntos arriba.",
  "residents_one": "{n} residente",
  "residents_other": "{n} residentes",
  "guests_one": "{n} invitado",
  "guests_other": "{n} invitados",
  "py_counts": "Pys {a}/{b} · Mascotas {c}/{d} · Peces {e}/{f}",
  "door_sp": "El estante, la pecera y las mascotas están vacíos hasta que los traigas de Pythoneer. Tu casa va contigo.",
  "visit": "Visitar",
  "take_to_app": "Llévalos a la app",
  "save_png": "Guardar casa como Skin PNG",
  "tag_resident": "Residente",
  "tag_guest": "Invitado",
  "btn_duel": "Duelo",
  "btn_challenge": "Retar",
  "btn_open_app": "Abrir en la app",
  "share_text": "{name} te reta. Písalo 3 veces en 30 segundos.",
  "link_copied": "Enlace copiado",
  "copy_prompt": "Copia este enlace",
  "bad_link": "No se pudo leer este enlace. Pide uno nuevo.",
  "privacy": "Privacidad",
  "privacy_title": "Privacidad",
  "privacy_p1": "Lo que dibujas y tu casa se quedan en este navegador. No se sube nada.",
  "privacy_p2": "Un enlace de reto lleva tu personaje después del #. Esa parte del enlace nunca llega a nuestro servidor; quien lo reciba puede ver el personaje.",
  "privacy_p3": "Contamos eventos anónimos de la página (por ejemplo, «empezó un duelo») con un número aleatorio nuevo en cada visita. Sin cookies, sin cuentas, sin guardar direcciones IP.",
  "privacy_p4": "La app Spriteer tiene su propia política en su ficha de la App Store. Preguntas: {email}.",
  "not_here": "Aquí no hay nada.",
  "draw_instead": "Mejor dibuja un personaje →"
 },
 "fr": {
  "page_title": "Spriteer — Trois images. Tous les jeux.",
  "page_title_c": "Un défi Spriteer",
  "get_app": "Obtenir l'app",
  "challenge_default": "Un défi",
  "challenge_lede": "Crée ton propre combattant ci-dessous — quatre points — puis saute 3 fois sur la tête du rival en 30 secondes.",
  "challenge_name": "{name} te défie",
  "h1": "Trois images. Tous les jeux.",
  "lede": "Chaque personnage, c'est Immobile · Marche · K.O. Remplis les quatre points de Marche et regarde-le marcher.",
  "idle": "Immobile",
  "walk": "Marche",
  "die": "K.O.",
  "live": "En direct",
  "goal_tap": "Touche les points qui clignotent sur Marche.",
  "goal_walks": "Il marche ! Le duel commence dans un instant…",
  "goal_ready": "Appuie sur Jouer dès que tu veux.",
  "play": "Jouer ▶",
  "another": "Autre croquis",
  "name_label": "Nom",
  "duel_title": "Duel de sauts",
  "rival_line": "Saute 3 fois sur la tête du rival en 30 secondes",
  "close": "Fermer",
  "move_left": "Aller à gauche",
  "move_right": "Aller à droite",
  "jump": "SAUT",
  "keys_line": "← → / A D  Bouger · Space ↑ W  Sauter · Esc  Fermer · Manette : A Sauter, B Fermer",
  "hud_you": "TOI {n}",
  "hud_rival": "{n} RIVAL",
  "hud_rule": "3 sauts · 30 s",
  "hud_go": "GO",
  "result_draw": "Égalité, {a}–{b}.",
  "result_won": "Gagné {a}–{b} !",
  "result_lost": "Le rival gagne {b}–{a}.",
  "moved_in": "{name} a emménagé chez toi · {n}",
  "guest_stays": "{name} reste comme invité.",
  "challenge_friend": "Défier un ami",
  "rematch": "Revanche",
  "draw_another": "En dessiner un autre",
  "your_house": "Ta maison",
  "house_lede": "Tous ceux que tu termines emménagent ici. Les Pys, animaux et poissons de Pythoneer vivent ici aussi.",
  "house_empty": "Personne n'habite ici pour l'instant — remplis quatre points ci-dessus.",
  "residents_one": "{n} habitant",
  "residents_other": "{n} habitants",
  "guests_one": "{n} invité",
  "guests_other": "{n} invités",
  "py_counts": "Pys {a}/{b} · Animaux {c}/{d} · Poissons {e}/{f}",
  "door_sp": "L'étagère, l'aquarium et les animaux restent vides jusqu'à ce que tu les ramènes de Pythoneer. Ta maison te suit.",
  "visit": "Visiter",
  "take_to_app": "Les emmener dans l'app",
  "save_png": "Enregistrer la maison en Skin PNG",
  "tag_resident": "Habitant",
  "tag_guest": "Invité",
  "btn_duel": "Duel",
  "btn_challenge": "Défier",
  "btn_open_app": "Ouvrir dans l'app",
  "share_text": "{name} te défie. Saute-lui 3 fois sur la tête en 30 secondes.",
  "link_copied": "Lien copié",
  "copy_prompt": "Copie ce lien",
  "bad_link": "Impossible de lire ce lien. Demande-en un nouveau.",
  "privacy": "Confidentialité",
  "privacy_title": "Confidentialité",
  "privacy_p1": "Tes dessins et ta maison restent dans ce navigateur. Rien n'est envoyé.",
  "privacy_p2": "Un lien de défi transporte ton personnage après le #. Cette partie d'un lien n'atteint jamais notre serveur ; la personne qui le reçoit peut voir le personnage.",
  "privacy_p3": "Nous comptons des événements de page anonymes (par exemple « un duel a commencé ») avec un nombre aléatoire créé à chaque visite. Pas de cookies, pas de comptes, aucune adresse IP conservée.",
  "privacy_p4": "L'app Spriteer a sa propre politique sur sa fiche App Store. Questions : {email}.",
  "not_here": "Rien ici.",
  "draw_instead": "Dessine plutôt un personnage →"
 },
 "hi": {
  "page_title": "Spriteer — तीन फ़्रेम। हर गेम।",
  "page_title_c": "एक Spriteer चुनौती",
  "get_app": "ऐप लो",
  "challenge_default": "एक चुनौती",
  "challenge_lede": "नीचे अपना लड़ाका बनाओ — चार बिंदु — फिर 30 सेकंड में विरोधी पर 3 बार कूदो।",
  "challenge_name": "{name} तुम्हें चुनौती देता है",
  "h1": "तीन फ़्रेम। हर गेम।",
  "lede": "हर किरदार में स्थिर · चलो · मरना होता है। चलो के चार बिंदु भरो और उसे चलते देखो।",
  "idle": "स्थिर",
  "walk": "चलो",
  "die": "मरना",
  "live": "लाइव",
  "goal_tap": "चलो पर टिमटिमाते बिंदुओं को छुओ।",
  "goal_walks": "यह चल रहा है! मुक़ाबला बस शुरू होने वाला है…",
  "goal_ready": "तैयार हो तो खेलो दबाओ।",
  "play": "खेलो ▶",
  "another": "दूसरा स्केच",
  "name_label": "नाम",
  "duel_title": "कूद मुक़ाबला",
  "rival_line": "30 सेकंड में विरोधी पर 3 बार कूदो",
  "close": "बंद करें",
  "move_left": "बाएँ चलो",
  "move_right": "दाएँ चलो",
  "jump": "कूदो",
  "keys_line": "← → / A D  चलो · Space ↑ W  कूदो · Esc  बंद · पैड: A कूदो, B बंद",
  "hud_you": "तुम {n}",
  "hud_rival": "{n} विरोधी",
  "hud_rule": "3 बार कूदो · 30 से.",
  "hud_go": "शुरू",
  "result_draw": "बराबरी, {a}–{b}।",
  "result_won": "तुम जीते {a}–{b}!",
  "result_lost": "विरोधी जीता {b}–{a}।",
  "moved_in": "{name} तुम्हारे घर आ गया · {n}",
  "guest_stays": "{name} तुम्हारा मेहमान बनकर रहेगा।",
  "challenge_friend": "दोस्त को चुनौती दो",
  "rematch": "फिर से मुक़ाबला",
  "draw_another": "एक और बनाओ",
  "your_house": "तुम्हारा घर",
  "house_lede": "जिसे भी तुम पूरा करते हो, वह यहाँ रहने आ जाता है। Pythoneer के पाई, पालतू और मछलियाँ भी यहीं रहते हैं।",
  "house_empty": "यहाँ अभी कोई नहीं रहता — ऊपर चार बिंदु भरो।",
  "residents_one": "{n} निवासी",
  "residents_other": "{n} निवासी",
  "guests_one": "{n} मेहमान",
  "guests_other": "{n} मेहमान",
  "py_counts": "पाई {a}/{b} · पालतू {c}/{d} · मछली {e}/{f}",
  "door_sp": "शेल्फ़, टैंक और पालतू तब तक खाली रहेंगे जब तक तुम उन्हें Pythoneer से नहीं लाते। तुम्हारा घर तुम्हारे साथ चलता है।",
  "visit": "देखो",
  "take_to_app": "उन्हें ऐप में ले जाओ",
  "save_png": "घर को Skin PNG के रूप में सहेजो",
  "tag_resident": "निवासी",
  "tag_guest": "मेहमान",
  "btn_duel": "मुक़ाबला",
  "btn_challenge": "चुनौती दो",
  "btn_open_app": "ऐप में खोलो",
  "share_text": "{name} तुम्हें चुनौती देता है। 30 सेकंड में उस पर 3 बार कूदो।",
  "link_copied": "लिंक कॉपी हो गया",
  "copy_prompt": "यह लिंक कॉपी करो",
  "bad_link": "यह लिंक पढ़ा नहीं जा सका। नया लिंक माँगो।",
  "privacy": "गोपनीयता",
  "privacy_title": "गोपनीयता",
  "privacy_p1": "तुम जो बनाते हो और तुम्हारा घर इसी ब्राउज़र में रहते हैं। कुछ भी अपलोड नहीं होता।",
  "privacy_p2": "चुनौती लिंक में तुम्हारा किरदार # के बाद होता है। लिंक का वह हिस्सा कभी हमारे सर्वर तक नहीं पहुँचता; जिसे तुम लिंक भेजते हो, वह किरदार देख सकता है।",
  "privacy_p3": "हम पेज की गुमनाम घटनाएँ गिनते हैं (जैसे \"एक मुक़ाबला शुरू हुआ\"), हर विज़िट पर नई बनी एक रैंडम संख्या के साथ। न कुकीज़, न खाते, और कोई IP पता नहीं रखा जाता।",
  "privacy_p4": "Spriteer ऐप की अपनी नीति App Store पेज पर है। सवाल: {email}।",
  "not_here": "यहाँ कुछ नहीं है।",
  "draw_instead": "इसके बजाय एक किरदार बनाओ →"
 },
 "id": {
  "page_title": "Spriteer — Tiga frame. Semua game.",
  "page_title_c": "Tantangan Spriteer",
  "get_app": "Dapatkan aplikasinya",
  "challenge_default": "Sebuah tantangan",
  "challenge_lede": "Buat petarungmu sendiri di bawah — empat titik — lalu injak lawan 3 kali dalam 30 detik.",
  "challenge_name": "{name} menantangmu",
  "h1": "Tiga frame. Semua game.",
  "lede": "Setiap karakter punya Diam · Jalan · Mati. Isi empat titik di Jalan dan lihat ia berjalan.",
  "idle": "Diam",
  "walk": "Jalan",
  "die": "Mati",
  "live": "Langsung",
  "goal_tap": "Ketuk titik yang berkedip di Jalan.",
  "goal_walks": "Ia berjalan! Duel segera dimulai…",
  "goal_ready": "Tekan Main kalau sudah siap.",
  "play": "Main ▶",
  "another": "Sketsa lain",
  "name_label": "Nama",
  "duel_title": "Duel injak",
  "rival_line": "Injak lawan 3 kali dalam 30 detik",
  "close": "Tutup",
  "move_left": "Gerak ke kiri",
  "move_right": "Gerak ke kanan",
  "jump": "LOMPAT",
  "keys_line": "← → / A D  Gerak · Space ↑ W  Lompat · Esc  Tutup · Pad: A Lompat, B Tutup",
  "hud_you": "KAMU {n}",
  "hud_rival": "{n} LAWAN",
  "hud_rule": "Injak 3 kali · 30 dtk",
  "hud_go": "MULAI",
  "result_draw": "Seri, {a}–{b}.",
  "result_won": "Kamu menang {a}–{b}!",
  "result_lost": "Lawan menang {b}–{a}.",
  "moved_in": "{name} pindah ke rumahmu · {n}",
  "guest_stays": "{name} tinggal sebagai tamumu.",
  "challenge_friend": "Tantang teman",
  "rematch": "Tanding ulang",
  "draw_another": "Gambar lagi",
  "your_house": "Rumahmu",
  "house_lede": "Semua yang kamu selesaikan pindah ke sini. Py, peliharaan, dan ikan dari Pythoneer juga tinggal di sini.",
  "house_empty": "Belum ada yang tinggal di sini — isi empat titik di atas.",
  "residents_one": "{n} penghuni",
  "residents_other": "{n} penghuni",
  "guests_one": "{n} tamu",
  "guests_other": "{n} tamu",
  "py_counts": "Py {a}/{b} · Peliharaan {c}/{d} · Ikan {e}/{f}",
  "door_sp": "Rak, akuarium, dan peliharaan kosong sampai kamu membawanya dari Pythoneer. Rumahmu ikut denganmu.",
  "visit": "Kunjungi",
  "take_to_app": "Bawa ke aplikasi",
  "save_png": "Simpan rumah sebagai Skin PNG",
  "tag_resident": "Penghuni",
  "tag_guest": "Tamu",
  "btn_duel": "Duel",
  "btn_challenge": "Tantang",
  "btn_open_app": "Buka di aplikasi",
  "share_text": "{name} menantangmu. Injak dia 3 kali dalam 30 detik.",
  "link_copied": "Tautan disalin",
  "copy_prompt": "Salin tautan ini",
  "bad_link": "Tautan ini tidak bisa dibaca. Minta tautan baru.",
  "privacy": "Privasi",
  "privacy_title": "Privasi",
  "privacy_p1": "Gambarmu dan rumahmu tetap di browser ini. Tidak ada yang diunggah.",
  "privacy_p2": "Tautan tantangan membawa karaktermu setelah tanda #. Bagian tautan itu tidak pernah sampai ke server kami; siapa pun yang kamu kirimi bisa melihat karakternya.",
  "privacy_p3": "Kami menghitung peristiwa halaman secara anonim (misalnya \"duel dimulai\") dengan angka acak yang dibuat baru di setiap kunjungan. Tanpa cookie, tanpa akun, tanpa menyimpan alamat IP.",
  "privacy_p4": "Aplikasi Spriteer punya kebijakannya sendiri di halaman App Store. Pertanyaan: {email}.",
  "not_here": "Tidak ada di sini.",
  "draw_instead": "Gambar karakter saja →"
 },
 "it": {
  "page_title": "Spriteer — Tre fotogrammi. Ogni gioco.",
  "page_title_c": "Una sfida Spriteer",
  "get_app": "Scarica l'app",
  "challenge_default": "Una sfida",
  "challenge_lede": "Crea qui sotto il tuo lottatore — quattro punti — poi saltagli in testa 3 volte in 30 secondi.",
  "challenge_name": "{name} ti sfida",
  "h1": "Tre fotogrammi. Ogni gioco.",
  "lede": "Ogni personaggio è Fermo · Cammina · Muori. Riempi i quattro punti di Cammina e guardalo camminare.",
  "idle": "Fermo",
  "walk": "Cammina",
  "die": "Muori",
  "live": "Live",
  "goal_tap": "Tocca i punti che lampeggiano su Cammina.",
  "goal_walks": "Cammina! Il duello inizia tra un attimo…",
  "goal_ready": "Premi Gioca quando sei pronto.",
  "play": "Gioca ▶",
  "another": "Un altro schizzo",
  "name_label": "Nome",
  "duel_title": "Duello a salti",
  "rival_line": "Salta in testa al rivale 3 volte in 30 secondi",
  "close": "Chiudi",
  "move_left": "Muovi a sinistra",
  "move_right": "Muovi a destra",
  "jump": "SALTA",
  "keys_line": "← → / A D  Muovi · Space ↑ W  Salta · Esc  Chiudi · Pad: A Salta, B Chiudi",
  "hud_you": "TU {n}",
  "hud_rival": "{n} RIVALE",
  "hud_rule": "3 salti · 30 s",
  "hud_go": "VIA",
  "result_draw": "Pareggio, {a}–{b}.",
  "result_won": "Hai vinto {a}–{b}!",
  "result_lost": "Ha vinto il rivale {b}–{a}.",
  "moved_in": "{name} si è trasferito a casa tua · {n}",
  "guest_stays": "{name} resta come tuo ospite.",
  "challenge_friend": "Sfida un amico",
  "rematch": "Rivincita",
  "draw_another": "Disegnane un altro",
  "your_house": "La tua casa",
  "house_lede": "Ogni personaggio che completi si trasferisce qui. Anche i Py, gli animali e i pesci di Pythoneer vivono qui.",
  "house_empty": "Qui non abita ancora nessuno — riempi i quattro punti qui sopra.",
  "residents_one": "{n} abitante",
  "residents_other": "{n} abitanti",
  "guests_one": "{n} ospite",
  "guests_other": "{n} ospiti",
  "py_counts": "Py {a}/{b} · Animali {c}/{d} · Pesci {e}/{f}",
  "door_sp": "Lo scaffale, la vasca e gli animali restano vuoti finché non li porti da Pythoneer. La tua casa viene con te.",
  "visit": "Visita",
  "take_to_app": "Portali nell'app",
  "save_png": "Salva la casa come Skin PNG",
  "tag_resident": "Abitante",
  "tag_guest": "Ospite",
  "btn_duel": "Duello",
  "btn_challenge": "Sfida",
  "btn_open_app": "Apri nell'app",
  "share_text": "{name} ti sfida. Saltagli in testa 3 volte in 30 secondi.",
  "link_copied": "Link copiato",
  "copy_prompt": "Copia questo link",
  "bad_link": "Impossibile leggere questo link. Chiedine uno nuovo.",
  "privacy": "Privacy",
  "privacy_title": "Privacy",
  "privacy_p1": "Ciò che disegni e la tua casa restano in questo browser. Non viene caricato nulla.",
  "privacy_p2": "Un link di sfida porta il tuo personaggio dopo il #. Quella parte del link non arriva mai al nostro server; chi lo riceve può vedere il personaggio.",
  "privacy_p3": "Contiamo eventi anonimi della pagina (per esempio \"è iniziato un duello\") con un numero casuale creato da zero a ogni visita. Niente cookie, niente account, nessun indirizzo IP conservato.",
  "privacy_p4": "L'app Spriteer ha una propria informativa nella pagina dell'App Store. Domande: {email}.",
  "not_here": "Qui non c'è niente.",
  "draw_instead": "Disegna invece un personaggio →"
 },
 "ja": {
  "page_title": "Spriteer — 3コマで、どのゲームにも。",
  "page_title_c": "Spriteerからの挑戦状",
  "get_app": "アプリを入手",
  "challenge_default": "挑戦状",
  "challenge_lede": "下で自分のキャラを作ろう（点は4つだけ）。それから30秒以内に相手を3回ふもう。",
  "challenge_name": "{name}からの挑戦状",
  "h1": "3コマで、どのゲームにも。",
  "lede": "キャラはみんなじっと・あるく・やられの3コマ。あるくの4つの点を塗ると歩きだす。",
  "idle": "じっと",
  "walk": "あるく",
  "die": "やられ",
  "live": "ライブ",
  "goal_tap": "あるくの点滅している点をタップ。",
  "goal_walks": "歩いた！もうすぐ対決…",
  "goal_ready": "準備ができたらプレイを押そう。",
  "play": "プレイ ▶",
  "another": "別の下絵",
  "name_label": "名前",
  "duel_title": "ふみつけ対決",
  "rival_line": "30秒以内に相手を3回ふもう",
  "close": "閉じる",
  "move_left": "左へ移動",
  "move_right": "右へ移動",
  "jump": "ジャンプ",
  "keys_line": "← → / A D 移動・Space ↑ W ジャンプ・Esc 閉じる・パッド: A ジャンプ、B 閉じる",
  "hud_you": "あなた {n}",
  "hud_rival": "{n} 相手",
  "hud_rule": "3回ふむ・30秒",
  "hud_go": "スタート",
  "result_draw": "引き分け {a}–{b}",
  "result_won": "勝ち！{a}–{b}",
  "result_lost": "相手の勝ち {b}–{a}",
  "moved_in": "{name}があなたの家に引っ越してきた・{n}",
  "guest_stays": "{name}はお客としてとどまる。",
  "challenge_friend": "友だちに挑戦状",
  "rematch": "再戦",
  "draw_another": "もう1体描く",
  "your_house": "あなたの家",
  "house_lede": "完成させたキャラはみんな引っ越してくる。Pythoneerのパイ、ペット、魚もここに住んでいる。",
  "house_empty": "まだ誰も住んでいない。上の4つの点を塗ろう。",
  "residents_one": "住人{n}",
  "residents_other": "住人{n}",
  "guests_one": "お客{n}",
  "guests_other": "お客{n}",
  "py_counts": "パイ {a}/{b}・ペット {c}/{d}・魚 {e}/{f}",
  "door_sp": "棚と水槽とペットは、Pythoneerから連れてくるまで空っぽ。あなたの家はどこへでも一緒。",
  "visit": "見に行く",
  "take_to_app": "アプリに連れていく",
  "save_png": "家をSkin PNGで保存",
  "tag_resident": "住人",
  "tag_guest": "お客",
  "btn_duel": "対決",
  "btn_challenge": "挑戦状",
  "btn_open_app": "アプリで開く",
  "share_text": "{name}からの挑戦状。30秒以内に3回ふもう。",
  "link_copied": "リンクをコピーしました",
  "copy_prompt": "このリンクをコピー",
  "bad_link": "このリンクは読めませんでした。新しいリンクをもらってください。",
  "privacy": "プライバシー",
  "privacy_title": "プライバシー",
  "privacy_p1": "描いたものとあなたの家は、このブラウザの中だけに残ります。何もアップロードしません。",
  "privacy_p2": "挑戦状のリンクは、#のあとにあなたのキャラを載せて運びます。リンクのこの部分は私たちのサーバーに届きません。リンクを送った相手にはキャラが見えます。",
  "privacy_p3": "匿名のページイベント（たとえば「対決が始まった」）を、訪問ごとに新しく作る乱数で数えています。Cookieなし、アカウントなし、IPアドレスは保存しません。",
  "privacy_p4": "SpriteerアプリのポリシーはApp Storeのページにあります。お問い合わせ: {email}。",
  "not_here": "ここには何もない。",
  "draw_instead": "かわりにキャラを描こう →"
 },
 "ko": {
  "page_title": "Spriteer — 세 장이면, 모든 게임.",
  "page_title_c": "Spriteer 도전장",
  "get_app": "앱 받기",
  "challenge_default": "도전장",
  "challenge_lede": "아래에서 내 캐릭터를 만들고(점 네 개면 돼요) 30초 안에 상대를 세 번 밟으세요.",
  "challenge_name": "{name}의 도전장",
  "h1": "세 장이면, 모든 게임.",
  "lede": "모든 캐릭터는 가만히 · 걷기 · 쓰러지기 세 칸. 걷기의 점 넷을 채우면 걷기 시작해요.",
  "idle": "가만히",
  "walk": "걷기",
  "die": "쓰러지기",
  "live": "실시간",
  "goal_tap": "걷기에서 깜빡이는 점을 누르세요.",
  "goal_walks": "걷는다! 곧 결투가 시작돼요…",
  "goal_ready": "준비되면 플레이를 누르세요.",
  "play": "플레이 ▶",
  "another": "다른 밑그림",
  "name_label": "이름",
  "duel_title": "밟기 결투",
  "rival_line": "30초 안에 상대를 세 번 밟으세요",
  "close": "닫기",
  "move_left": "왼쪽으로 이동",
  "move_right": "오른쪽으로 이동",
  "jump": "점프",
  "keys_line": "← → / A D 이동 · Space ↑ W 점프 · Esc 닫기 · 패드: A 점프, B 닫기",
  "hud_you": "나 {n}",
  "hud_rival": "{n} 상대",
  "hud_rule": "세 번 밟기 · 30초",
  "hud_go": "시작",
  "result_draw": "비겼어요, {a}–{b}.",
  "result_won": "이겼어요! {a}–{b}",
  "result_lost": "상대가 이겼어요, {b}–{a}.",
  "moved_in": "{name}, 내 집에 이사 왔어요 · {n}",
  "guest_stays": "{name}, 손님으로 머물러요.",
  "challenge_friend": "친구에게 도전장",
  "rematch": "다시 붙기",
  "draw_another": "하나 더 그리기",
  "your_house": "내 집",
  "house_lede": "완성한 캐릭터는 모두 이사 와요. Pythoneer의 파이, 반려동물, 물고기도 여기 살아요.",
  "house_empty": "아직 아무도 안 살아요. 위에서 점 네 개를 채워 보세요.",
  "residents_one": "주민 {n}",
  "residents_other": "주민 {n}",
  "guests_one": "손님 {n}",
  "guests_other": "손님 {n}",
  "py_counts": "파이 {a}/{b} · 반려동물 {c}/{d} · 물고기 {e}/{f}",
  "door_sp": "선반, 수조, 반려동물 자리는 Pythoneer에서 데려오기 전까지 비어 있어요. 내 집은 어디든 함께 가요.",
  "visit": "놀러 가기",
  "take_to_app": "앱으로 데려가기",
  "save_png": "집을 Skin PNG로 저장",
  "tag_resident": "주민",
  "tag_guest": "손님",
  "btn_duel": "결투",
  "btn_challenge": "도전장",
  "btn_open_app": "앱에서 열기",
  "share_text": "{name}의 도전장. 30초 안에 세 번 밟아 보세요.",
  "link_copied": "링크를 복사했어요",
  "copy_prompt": "이 링크를 복사하세요",
  "bad_link": "링크를 읽지 못했어요. 새 링크를 받아 주세요.",
  "privacy": "개인정보",
  "privacy_title": "개인정보",
  "privacy_p1": "그린 그림과 내 집은 이 브라우저에만 남아요. 아무것도 올리지 않아요.",
  "privacy_p2": "도전장 링크는 # 뒤에 캐릭터를 담아 보내요. 링크의 이 부분은 저희 서버에 닿지 않아요. 링크를 받은 사람은 캐릭터를 볼 수 있어요.",
  "privacy_p3": "방문할 때마다 새로 만드는 임의의 숫자로 익명 페이지 이벤트(예: \"결투 시작\")를 세요. 쿠키도, 계정도 없고, IP 주소도 보관하지 않아요.",
  "privacy_p4": "Spriteer 앱의 개인정보 처리방침은 App Store 페이지에 따로 있어요. 문의: {email}.",
  "not_here": "여기엔 없어요.",
  "draw_instead": "대신 캐릭터 그리기 →"
 },
 "nl": {
  "page_title": "Spriteer — Drie frames. Elk spel.",
  "page_title_c": "Een Spriteer-uitdaging",
  "get_app": "Download de app",
  "challenge_default": "Een uitdaging",
  "challenge_lede": "Maak hieronder je eigen vechter — vier punten — en spring er dan 3 keer op in 30 seconden.",
  "challenge_name": "{name} daagt je uit",
  "h1": "Drie frames. Elk spel.",
  "lede": "Elk personage is Stil · Lopen · Doodgaan. Vul de vier punten bij Lopen en zie het lopen.",
  "idle": "Stil",
  "walk": "Lopen",
  "die": "Doodgaan",
  "live": "Live",
  "goal_tap": "Tik op de knipperende punten bij Lopen.",
  "goal_walks": "Het loopt! Het duel begint zo…",
  "goal_ready": "Druk op Spelen als je klaar bent.",
  "play": "Spelen ▶",
  "another": "Andere schets",
  "name_label": "Naam",
  "duel_title": "Springduel",
  "rival_line": "Spring 3 keer op je rivaal in 30 seconden",
  "close": "Sluiten",
  "move_left": "Naar links",
  "move_right": "Naar rechts",
  "jump": "SPRING",
  "keys_line": "← → / A D  Lopen · Space ↑ W  Springen · Esc  Sluiten · Pad: A Springen, B Sluiten",
  "hud_you": "JIJ {n}",
  "hud_rival": "{n} RIVAAL",
  "hud_rule": "3 keer springen · 30 s",
  "hud_go": "START",
  "result_draw": "Gelijkspel, {a}–{b}.",
  "result_won": "Gewonnen, {a}–{b}!",
  "result_lost": "De rivaal wint, {b}–{a}.",
  "moved_in": "{name} is in je huis getrokken · {n}",
  "guest_stays": "{name} blijft als je gast.",
  "challenge_friend": "Daag een vriend uit",
  "rematch": "Revanche",
  "draw_another": "Teken er nog een",
  "your_house": "Jouw huis",
  "house_lede": "Elk personage dat je af hebt, trekt bij je in. Ook de Py's, huisdieren en vissen van Pythoneer wonen hier.",
  "house_empty": "Hier woont nog niemand — vul hierboven vier punten.",
  "residents_one": "{n} bewoner",
  "residents_other": "{n} bewoners",
  "guests_one": "{n} gast",
  "guests_other": "{n} gasten",
  "py_counts": "Py's {a}/{b} · Huisdieren {c}/{d} · Vissen {e}/{f}",
  "door_sp": "De plank, het aquarium en de huisdieren blijven leeg tot je ze uit Pythoneer meeneemt. Je huis gaat met je mee.",
  "visit": "Bezoeken",
  "take_to_app": "Neem ze mee naar de app",
  "save_png": "Huis bewaren als Skin PNG",
  "tag_resident": "Bewoner",
  "tag_guest": "Gast",
  "btn_duel": "Duel",
  "btn_challenge": "Uitdagen",
  "btn_open_app": "Openen in app",
  "share_text": "{name} daagt je uit. Spring er 3 keer op in 30 seconden.",
  "link_copied": "Link gekopieerd",
  "copy_prompt": "Kopieer deze link",
  "bad_link": "Deze link kon niet worden gelezen. Vraag om een nieuwe.",
  "privacy": "Privacy",
  "privacy_title": "Privacy",
  "privacy_p1": "Wat je tekent en je huis blijven in deze browser. Er wordt niets geüpload.",
  "privacy_p2": "Een uitdagingslink draagt je personage na de #. Dat deel van een link bereikt onze server nooit; wie je de link stuurt, kan het personage zien.",
  "privacy_p3": "We tellen anonieme paginagebeurtenissen (bijvoorbeeld \"er is een duel begonnen\") met een willekeurig getal dat bij elk bezoek nieuw wordt gemaakt. Geen cookies, geen accounts, geen IP-adressen bewaard.",
  "privacy_p4": "De Spriteer-app heeft een eigen beleid op de App Store-pagina. Vragen: {email}.",
  "not_here": "Niet hier.",
  "draw_instead": "Teken liever een personage →"
 },
 "pt-BR": {
  "page_title": "Spriteer — Três quadros. Todo jogo.",
  "page_title_c": "Um desafio Spriteer",
  "get_app": "Baixe o app",
  "challenge_default": "Um desafio",
  "challenge_lede": "Crie seu lutador aqui embaixo — quatro pontos — e depois pule nele 3 vezes em 30 segundos.",
  "challenge_name": "{name} desafia você",
  "h1": "Três quadros. Todo jogo.",
  "lede": "Todo personagem tem Parado · Andar · Morrer. Preencha os quatro pontos de Andar e veja-o andar.",
  "idle": "Parado",
  "walk": "Andar",
  "die": "Morrer",
  "live": "Ao vivo",
  "goal_tap": "Toque nos pontos piscando em Andar.",
  "goal_walks": "Ele anda! O duelo começa em instantes…",
  "goal_ready": "Aperte Jogar quando estiver pronto.",
  "play": "Jogar ▶",
  "another": "Outro esboço",
  "name_label": "Nome",
  "duel_title": "Duelo de pulos",
  "rival_line": "Pule no rival 3 vezes em 30 segundos",
  "close": "Fechar",
  "move_left": "Mover para a esquerda",
  "move_right": "Mover para a direita",
  "jump": "PULAR",
  "keys_line": "← → / A D  Mover · Space ↑ W  Pular · Esc  Fechar · Controle: A Pular, B Fechar",
  "hud_you": "VOCÊ {n}",
  "hud_rival": "{n} RIVAL",
  "hud_rule": "Pule 3 vezes · 30 s",
  "hud_go": "JÁ",
  "result_draw": "Empate, {a}–{b}.",
  "result_won": "Você venceu {a}–{b}!",
  "result_lost": "O rival venceu {b}–{a}.",
  "moved_in": "{name} se mudou para sua casa · {n}",
  "guest_stays": "{name} fica como sua visita.",
  "challenge_friend": "Desafie um amigo",
  "rematch": "Revanche",
  "draw_another": "Desenhar outro",
  "your_house": "Sua casa",
  "house_lede": "Todo personagem que você termina se muda para cá. Os Pys, bichos e peixes do Pythoneer também moram aqui.",
  "house_empty": "Ninguém mora aqui ainda — preencha os quatro pontos acima.",
  "residents_one": "{n} morador",
  "residents_other": "{n} moradores",
  "guests_one": "{n} visita",
  "guests_other": "{n} visitas",
  "py_counts": "Pys {a}/{b} · Bichos {c}/{d} · Peixes {e}/{f}",
  "door_sp": "A estante, o aquário e os bichos ficam vazios até você trazê-los do Pythoneer. Sua casa vai com você.",
  "visit": "Visitar",
  "take_to_app": "Levar para o app",
  "save_png": "Salvar casa como Skin PNG",
  "tag_resident": "Morador",
  "tag_guest": "Visita",
  "btn_duel": "Duelo",
  "btn_challenge": "Desafiar",
  "btn_open_app": "Abrir no app",
  "share_text": "{name} desafia você. Pule nele 3 vezes em 30 segundos.",
  "link_copied": "Link copiado",
  "copy_prompt": "Copie este link",
  "bad_link": "Não foi possível ler este link. Peça um novo.",
  "privacy": "Privacidade",
  "privacy_title": "Privacidade",
  "privacy_p1": "O que você desenha e sua casa ficam neste navegador. Nada é enviado.",
  "privacy_p2": "Um link de desafio leva seu personagem depois do #. Essa parte do link nunca chega ao nosso servidor; quem recebe o link pode ver o personagem.",
  "privacy_p3": "Contamos eventos anônimos da página (por exemplo, \"um duelo começou\") com um número aleatório novo a cada visita. Sem cookies, sem contas, sem guardar endereços IP.",
  "privacy_p4": "O app Spriteer tem sua própria política na página da App Store. Dúvidas: {email}.",
  "not_here": "Nada aqui.",
  "draw_instead": "Desenhe um personagem →"
 },
 "ru": {
  "page_title": "Spriteer — Три кадра. Любая игра.",
  "page_title_c": "Вызов из Spriteer",
  "get_app": "Скачать приложение",
  "challenge_default": "Вызов",
  "challenge_lede": "Создай ниже своего бойца — всего четыре точки — и прыгни сопернику на голову 3 раза за 30 секунд.",
  "challenge_name": "{name} бросает тебе вызов",
  "h1": "Три кадра. Любая игра.",
  "lede": "У каждого персонажа три кадра: Стоит · Идёт · Умереть. Заполни четыре точки в «Идёт» — и он пойдёт.",
  "idle": "Стоит",
  "walk": "Идёт",
  "die": "Умереть",
  "live": "Вживую",
  "goal_tap": "Нажми на мигающие точки в «Идёт».",
  "goal_walks": "Идёт! Дуэль вот-вот начнётся…",
  "goal_ready": "Нажми «Играть», когда будешь готов.",
  "play": "Играть ▶",
  "another": "Другой набросок",
  "name_label": "Имя",
  "duel_title": "Дуэль прыжков",
  "rival_line": "Прыгни сопернику на голову 3 раза за 30 секунд",
  "close": "Закрыть",
  "move_left": "Влево",
  "move_right": "Вправо",
  "jump": "ПРЫЖОК",
  "keys_line": "← → / A D  Ходить · Space ↑ W  Прыжок · Esc  Закрыть · Геймпад: A — прыжок, B — закрыть",
  "hud_you": "ТЫ {n}",
  "hud_rival": "{n} СОПЕРНИК",
  "hud_rule": "3 прыжка · 30 с",
  "hud_go": "СТАРТ",
  "result_draw": "Ничья, {a}–{b}.",
  "result_won": "Победа {a}–{b}!",
  "result_lost": "Победил соперник, {b}–{a}.",
  "moved_in": "{name} переехал к тебе · {n}",
  "guest_stays": "{name} остаётся у тебя в гостях.",
  "challenge_friend": "Вызвать друга",
  "rematch": "Реванш",
  "draw_another": "Нарисовать ещё",
  "your_house": "Твой дом",
  "house_lede": "Каждый готовый персонаж переезжает сюда. Паи, питомцы и рыбы из Pythoneer тоже живут здесь.",
  "house_empty": "Здесь пока никто не живёт — заполни четыре точки выше.",
  "residents_one": "Жильцов: {n}",
  "residents_other": "Жильцов: {n}",
  "guests_one": "Гостей: {n}",
  "guests_other": "Гостей: {n}",
  "py_counts": "Паи {a}/{b} · Питомцы {c}/{d} · Рыбы {e}/{f}",
  "door_sp": "Полка, аквариум и питомцы пустуют, пока ты не приведёшь их из Pythoneer. Твой дом всегда с тобой.",
  "visit": "В гости",
  "take_to_app": "Забрать в приложение",
  "save_png": "Сохранить дом как Skin PNG",
  "tag_resident": "Жилец",
  "tag_guest": "Гость",
  "btn_duel": "Дуэль",
  "btn_challenge": "Вызов",
  "btn_open_app": "Открыть в приложении",
  "share_text": "{name} бросает тебе вызов. Прыгни ему на голову 3 раза за 30 секунд.",
  "link_copied": "Ссылка скопирована",
  "copy_prompt": "Скопируй эту ссылку",
  "bad_link": "Не удалось прочитать ссылку. Попроси новую.",
  "privacy": "Конфиденциальность",
  "privacy_title": "Конфиденциальность",
  "privacy_p1": "Твои рисунки и твой дом остаются в этом браузере. Ничего не загружается.",
  "privacy_p2": "Ссылка-вызов несёт твоего персонажа после #. Эта часть ссылки никогда не попадает на наш сервер; тот, кому ты её отправишь, увидит персонажа.",
  "privacy_p3": "Мы считаем анонимные события страницы (например, «началась дуэль») со случайным числом, новым для каждого визита. Без cookie, без аккаунтов, IP-адреса не хранятся.",
  "privacy_p4": "У приложения Spriteer своя политика на странице в App Store. Вопросы: {email}.",
  "not_here": "Здесь ничего нет.",
  "draw_instead": "Лучше нарисуй персонажа →",
  "residents_few": "Жильцов: {n}",
  "residents_many": "Жильцов: {n}",
  "guests_few": "Гостей: {n}",
  "guests_many": "Гостей: {n}"
 },
 "sv": {
  "page_title": "Spriteer — Tre bilder. Varje spel.",
  "page_title_c": "En Spriteer-utmaning",
  "get_app": "Hämta appen",
  "challenge_default": "En utmaning",
  "challenge_lede": "Gör din egen kämpe nedan — fyra prickar — och hoppa sedan på den 3 gånger på 30 sekunder.",
  "challenge_name": "{name} utmanar dig",
  "h1": "Tre bilder. Varje spel.",
  "lede": "Varje figur är Stilla · Gå · Dö. Fyll de fyra prickarna på Gå och se den gå.",
  "idle": "Stilla",
  "walk": "Gå",
  "die": "Dö",
  "live": "Live",
  "goal_tap": "Tryck på de blinkande prickarna på Gå.",
  "goal_walks": "Den går! Duellen börjar strax…",
  "goal_ready": "Tryck på Spela när du är redo.",
  "play": "Spela ▶",
  "another": "En skiss till",
  "name_label": "Namn",
  "duel_title": "Hoppduell",
  "rival_line": "Hoppa på rivalen 3 gånger på 30 sekunder",
  "close": "Stäng",
  "move_left": "Gå vänster",
  "move_right": "Gå höger",
  "jump": "HOPPA",
  "keys_line": "← → / A D  Gå · Space ↑ W  Hoppa · Esc  Stäng · Handkontroll: A Hoppa, B Stäng",
  "hud_you": "DU {n}",
  "hud_rival": "{n} RIVAL",
  "hud_rule": "3 hopp · 30 s",
  "hud_go": "KÖR",
  "result_draw": "Oavgjort, {a}–{b}.",
  "result_won": "Du vann {a}–{b}!",
  "result_lost": "Rivalen vann {b}–{a}.",
  "moved_in": "{name} har flyttat in i ditt hus · {n}",
  "guest_stays": "{name} stannar som din gäst.",
  "challenge_friend": "Utmana en vän",
  "rematch": "Returmatch",
  "draw_another": "Rita en till",
  "your_house": "Ditt hus",
  "house_lede": "Alla du gör klart flyttar in. Pythoneers Py, husdjur och fiskar bor här också.",
  "house_empty": "Ingen bor här än — fyll fyra prickar ovan.",
  "residents_one": "{n} invånare",
  "residents_other": "{n} invånare",
  "guests_one": "{n} gäst",
  "guests_other": "{n} gäster",
  "py_counts": "Py {a}/{b} · Husdjur {c}/{d} · Fiskar {e}/{f}",
  "door_sp": "Hyllan, akvariet och husdjuren är tomma tills du tar med dem från Pythoneer. Ditt hus följer med dig.",
  "visit": "Besök",
  "take_to_app": "Ta med dem till appen",
  "save_png": "Spara huset som Skin PNG",
  "tag_resident": "Invånare",
  "tag_guest": "Gäst",
  "btn_duel": "Duell",
  "btn_challenge": "Utmana",
  "btn_open_app": "Öppna i appen",
  "share_text": "{name} utmanar dig. Hoppa på den 3 gånger på 30 sekunder.",
  "link_copied": "Länken kopierad",
  "copy_prompt": "Kopiera den här länken",
  "bad_link": "Länken kunde inte läsas. Be om en ny.",
  "privacy": "Integritet",
  "privacy_title": "Integritet",
  "privacy_p1": "Det du ritar och ditt hus stannar i den här webbläsaren. Inget laddas upp.",
  "privacy_p2": "En utmaningslänk bär din figur efter #. Den delen av en länk når aldrig vår server; den du skickar den till kan se figuren.",
  "privacy_p3": "Vi räknar anonyma sidhändelser (till exempel \"en duell startade\") med ett slumptal som skapas på nytt vid varje besök. Inga kakor, inga konton, inga IP-adresser sparas.",
  "privacy_p4": "Spriteer-appen har en egen policy på sin sida i App Store. Frågor: {email}.",
  "not_here": "Inte här.",
  "draw_instead": "Rita en figur i stället →"
 },
 "th": {
  "page_title": "Spriteer — สามเฟรม ทุกเกม",
  "page_title_c": "คำท้าจาก Spriteer",
  "get_app": "ดาวน์โหลดแอป",
  "challenge_default": "คำท้า",
  "challenge_lede": "สร้างนักสู้ของคุณเองด้านล่าง — แค่สี่จุด — แล้วเหยียบมันให้ได้ 3 ครั้งใน 30 วินาที",
  "challenge_name": "{name} ท้าคุณ",
  "h1": "สามเฟรม ทุกเกม",
  "lede": "ทุกตัวละครมี อยู่นิ่ง · เดิน · ตาย เติมจุดสี่จุดใน เดิน แล้วดูมันเดิน",
  "idle": "อยู่นิ่ง",
  "walk": "เดิน",
  "die": "ตาย",
  "live": "สด",
  "goal_tap": "แตะจุดที่กะพริบใน เดิน",
  "goal_walks": "เดินแล้ว! อีกเดี๋ยวเริ่มดวล…",
  "goal_ready": "พร้อมแล้วกด เล่น",
  "play": "เล่น ▶",
  "another": "ภาพร่างอื่น",
  "name_label": "ชื่อ",
  "duel_title": "ดวลเหยียบหัว",
  "rival_line": "เหยียบหัวคู่แข่ง 3 ครั้งใน 30 วินาที",
  "close": "ปิด",
  "move_left": "ไปซ้าย",
  "move_right": "ไปขวา",
  "jump": "กระโดด",
  "keys_line": "← → / A D  เดิน · Space ↑ W  กระโดด · Esc  ปิด · จอย: A กระโดด, B ปิด",
  "hud_you": "คุณ {n}",
  "hud_rival": "{n} คู่แข่ง",
  "hud_rule": "เหยียบ 3 ครั้ง · 30 วิ",
  "hud_go": "ไป!",
  "result_draw": "เสมอ {a}–{b}",
  "result_won": "คุณชนะ {a}–{b}!",
  "result_lost": "คู่แข่งชนะ {b}–{a}",
  "moved_in": "{name} ย้ายเข้าบ้านของคุณแล้ว · {n}",
  "guest_stays": "{name} อยู่เป็นแขกของคุณ",
  "challenge_friend": "ท้าเพื่อน",
  "rematch": "แข่งอีกรอบ",
  "draw_another": "วาดอีกตัว",
  "your_house": "บ้านของคุณ",
  "house_lede": "ทุกตัวที่คุณทำเสร็จจะย้ายเข้ามา ไพ สัตว์เลี้ยง และปลาจาก Pythoneer ก็อยู่ที่นี่ด้วย",
  "house_empty": "ยังไม่มีใครอยู่ที่นี่ — เติมสี่จุดด้านบนก่อน",
  "residents_one": "ผู้อยู่อาศัย {n}",
  "residents_other": "ผู้อยู่อาศัย {n}",
  "guests_one": "แขก {n}",
  "guests_other": "แขก {n}",
  "py_counts": "ไพ {a}/{b} · สัตว์เลี้ยง {c}/{d} · ปลา {e}/{f}",
  "door_sp": "ชั้นวาง ตู้ปลา และสัตว์เลี้ยงจะว่างจนกว่าคุณจะพามาจาก Pythoneer บ้านของคุณไปกับคุณทุกที่",
  "visit": "แวะไปดู",
  "take_to_app": "พาไปที่แอป",
  "save_png": "บันทึกบ้านเป็น Skin PNG",
  "tag_resident": "ผู้อยู่อาศัย",
  "tag_guest": "แขก",
  "btn_duel": "ดวล",
  "btn_challenge": "ท้า",
  "btn_open_app": "เปิดในแอป",
  "share_text": "{name} ท้าคุณ เหยียบให้ได้ 3 ครั้งใน 30 วินาที",
  "link_copied": "คัดลอกลิงก์แล้ว",
  "copy_prompt": "คัดลอกลิงก์นี้",
  "bad_link": "อ่านลิงก์นี้ไม่ได้ ขอลิงก์ใหม่นะ",
  "privacy": "ความเป็นส่วนตัว",
  "privacy_title": "ความเป็นส่วนตัว",
  "privacy_p1": "สิ่งที่คุณวาดและบ้านของคุณอยู่ในเบราว์เซอร์นี้เท่านั้น ไม่มีอะไรถูกอัปโหลด",
  "privacy_p2": "ลิงก์คำท้าเก็บตัวละครของคุณไว้หลังเครื่องหมาย # ส่วนนั้นของลิงก์ไม่เคยไปถึงเซิร์ฟเวอร์ของเรา คนที่คุณส่งให้จะเห็นตัวละครนั้นได้",
  "privacy_p3": "เรานับเหตุการณ์บนหน้าเว็บแบบไม่ระบุตัวตน (เช่น \"เริ่มดวลแล้ว\") ด้วยตัวเลขสุ่มที่สร้างใหม่ทุกครั้งที่เข้าชม ไม่มีคุกกี้ ไม่มีบัญชี ไม่เก็บที่อยู่ IP",
  "privacy_p4": "แอป Spriteer มีนโยบายของตัวเองในหน้า App Store สอบถาม: {email}",
  "not_here": "ไม่มีที่นี่",
  "draw_instead": "ไปวาดตัวละครแทน →"
 },
 "tr": {
  "page_title": "Spriteer — Üç kare. Her oyun.",
  "page_title_c": "Bir Spriteer meydan okuması",
  "get_app": "Uygulamayı indir",
  "challenge_default": "Bir meydan okuma",
  "challenge_lede": "Aşağıda kendi dövüşçünü yap — dört nokta — sonra 30 saniyede kafasına 3 kez zıpla.",
  "challenge_name": "{name} sana meydan okuyor",
  "h1": "Üç kare. Her oyun.",
  "lede": "Her karakter Duruyor · Yürü · Öl. Yürü karesindeki dört noktayı doldur, yürüdüğünü gör.",
  "idle": "Duruyor",
  "walk": "Yürü",
  "die": "Öl",
  "live": "Canlı",
  "goal_tap": "Yürü karesinde yanıp sönen noktalara dokun.",
  "goal_walks": "Yürüyor! Düello birazdan başlıyor…",
  "goal_ready": "Hazır olunca Oyna'ya bas.",
  "play": "Oyna ▶",
  "another": "Başka bir taslak",
  "name_label": "Ad",
  "duel_title": "Zıplama düellosu",
  "rival_line": "30 saniyede rakibin kafasına 3 kez zıpla",
  "close": "Kapat",
  "move_left": "Sola git",
  "move_right": "Sağa git",
  "jump": "ZIPLA",
  "keys_line": "← → / A D  Yürü · Space ↑ W  Zıpla · Esc  Kapat · Kol: A Zıpla, B Kapat",
  "hud_you": "SEN {n}",
  "hud_rival": "{n} RAKİP",
  "hud_rule": "3 zıpla · 30 sn",
  "hud_go": "BAŞLA",
  "result_draw": "Berabere, {a}–{b}.",
  "result_won": "Kazandın {a}–{b}!",
  "result_lost": "Rakip kazandı {b}–{a}.",
  "moved_in": "{name} evine taşındı · {n}",
  "guest_stays": "{name} misafirin olarak kalıyor.",
  "challenge_friend": "Arkadaşına meydan oku",
  "rematch": "Rövanş",
  "draw_another": "Bir tane daha çiz",
  "your_house": "Evin",
  "house_lede": "Bitirdiğin herkes buraya taşınır. Pythoneer'daki Py, evcil hayvan ve balıklar da burada yaşar.",
  "house_empty": "Burada henüz kimse yaşamıyor — yukarıdaki dört noktayı doldur.",
  "residents_one": "{n} sakin",
  "residents_other": "{n} sakin",
  "guests_one": "{n} misafir",
  "guests_other": "{n} misafir",
  "py_counts": "Py {a}/{b} · Evcil {c}/{d} · Balık {e}/{f}",
  "door_sp": "Raf, akvaryum ve evcil hayvanlar, onları Pythoneer'dan getirene kadar boş kalır. Evin seninle gelir.",
  "visit": "Ziyaret et",
  "take_to_app": "Onları uygulamaya götür",
  "save_png": "Evi Skin PNG olarak kaydet",
  "tag_resident": "Sakin",
  "tag_guest": "Misafir",
  "btn_duel": "Düello",
  "btn_challenge": "Meydan oku",
  "btn_open_app": "Uygulamada aç",
  "share_text": "{name} sana meydan okuyor. 30 saniyede kafasına 3 kez zıpla.",
  "link_copied": "Bağlantı kopyalandı",
  "copy_prompt": "Bu bağlantıyı kopyala",
  "bad_link": "Bu bağlantı okunamadı. Yenisini iste.",
  "privacy": "Gizlilik",
  "privacy_title": "Gizlilik",
  "privacy_p1": "Çizdiklerin ve evin bu tarayıcıda kalır. Hiçbir şey yüklenmez.",
  "privacy_p2": "Meydan okuma bağlantısı karakterini # işaretinden sonra taşır. Bağlantının o kısmı sunucumuza hiç ulaşmaz; gönderdiğin kişi karakteri görebilir.",
  "privacy_p3": "Anonim sayfa olaylarını (örneğin \"bir düello başladı\") her ziyarette yeniden üretilen rastgele bir sayıyla sayarız. Çerez yok, hesap yok, IP adresi saklanmaz.",
  "privacy_p4": "Spriteer uygulamasının App Store sayfasında kendi politikası var. Sorular: {email}.",
  "not_here": "Burada değil.",
  "draw_instead": "Bunun yerine bir karakter çiz →"
 },
 "vi": {
  "page_title": "Spriteer — Ba khung. Mọi trò chơi.",
  "page_title_c": "Lời thách đấu Spriteer",
  "get_app": "Tải ứng dụng",
  "challenge_default": "Một lời thách đấu",
  "challenge_lede": "Tự tạo chiến binh của bạn bên dưới — bốn chấm — rồi nhảy lên đầu nó 3 lần trong 30 giây.",
  "challenge_name": "{name} thách đấu bạn",
  "h1": "Ba khung. Mọi trò chơi.",
  "lede": "Mỗi nhân vật gồm Đứng yên · Đi · Chết. Tô bốn chấm ở Đi và xem nó bước đi.",
  "idle": "Đứng yên",
  "walk": "Đi",
  "die": "Chết",
  "live": "Trực tiếp",
  "goal_tap": "Chạm vào các chấm đang nhấp nháy ở Đi.",
  "goal_walks": "Nó đi rồi! Trận đấu sắp bắt đầu…",
  "goal_ready": "Nhấn Chơi khi sẵn sàng.",
  "play": "Chơi ▶",
  "another": "Bản phác khác",
  "name_label": "Tên",
  "duel_title": "Đấu nhảy đầu",
  "rival_line": "Nhảy lên đầu đối thủ 3 lần trong 30 giây",
  "close": "Đóng",
  "move_left": "Sang trái",
  "move_right": "Sang phải",
  "jump": "NHẢY",
  "keys_line": "← → / A D  Di chuyển · Space ↑ W  Nhảy · Esc  Đóng · Tay cầm: A Nhảy, B Đóng",
  "hud_you": "BẠN {n}",
  "hud_rival": "{n} ĐỐI THỦ",
  "hud_rule": "Nhảy 3 lần · 30 giây",
  "hud_go": "ĐI!",
  "result_draw": "Hòa, {a}–{b}.",
  "result_won": "Bạn thắng {a}–{b}!",
  "result_lost": "Đối thủ thắng {b}–{a}.",
  "moved_in": "{name} đã dọn vào nhà bạn · {n}",
  "guest_stays": "{name} ở lại làm khách của bạn.",
  "challenge_friend": "Thách đấu bạn bè",
  "rematch": "Đấu lại",
  "draw_another": "Vẽ thêm một nhân vật",
  "your_house": "Nhà của bạn",
  "house_lede": "Ai bạn hoàn thành cũng dọn vào đây. Py, thú cưng và cá của Pythoneer cũng sống ở đây.",
  "house_empty": "Chưa có ai sống ở đây — hãy tô bốn chấm phía trên.",
  "residents_one": "{n} cư dân",
  "residents_other": "{n} cư dân",
  "guests_one": "{n} khách",
  "guests_other": "{n} khách",
  "py_counts": "Py {a}/{b} · Thú cưng {c}/{d} · Cá {e}/{f}",
  "door_sp": "Kệ, bể cá và thú cưng sẽ trống cho đến khi bạn mang chúng từ Pythoneer sang. Ngôi nhà luôn đi cùng bạn.",
  "visit": "Ghé thăm",
  "take_to_app": "Mang chúng vào ứng dụng",
  "save_png": "Lưu nhà thành Skin PNG",
  "tag_resident": "Cư dân",
  "tag_guest": "Khách",
  "btn_duel": "Đấu",
  "btn_challenge": "Thách đấu",
  "btn_open_app": "Mở trong ứng dụng",
  "share_text": "{name} thách đấu bạn. Nhảy lên đầu nó 3 lần trong 30 giây.",
  "link_copied": "Đã sao chép liên kết",
  "copy_prompt": "Sao chép liên kết này",
  "bad_link": "Không đọc được liên kết này. Hãy xin liên kết mới.",
  "privacy": "Quyền riêng tư",
  "privacy_title": "Quyền riêng tư",
  "privacy_p1": "Những gì bạn vẽ và ngôi nhà của bạn chỉ ở trong trình duyệt này. Không có gì được tải lên.",
  "privacy_p2": "Liên kết thách đấu mang nhân vật của bạn sau dấu #. Phần đó của liên kết không bao giờ đến máy chủ của chúng tôi; người nhận liên kết có thể thấy nhân vật.",
  "privacy_p3": "Chúng tôi đếm các sự kiện trang ẩn danh (ví dụ \"một trận đấu đã bắt đầu\") bằng một số ngẫu nhiên tạo mới cho mỗi lần truy cập. Không cookie, không tài khoản, không lưu địa chỉ IP.",
  "privacy_p4": "Ứng dụng Spriteer có chính sách riêng trên trang App Store. Thắc mắc: {email}.",
  "not_here": "Không có ở đây.",
  "draw_instead": "Vẽ một nhân vật thay vào đó →"
 },
 "zh-Hans": {
  "page_title": "Spriteer — 三帧，每个游戏。",
  "page_title_c": "Spriteer 挑战",
  "get_app": "获取 App",
  "challenge_default": "一个挑战",
  "challenge_lede": "在下面画一个你自己的斗士——四个点就够——然后在 30 秒内踩它 3 次。",
  "challenge_name": "{name} 向你挑战",
  "h1": "三帧，每个游戏。",
  "lede": "每个角色都有站立 · 行走 · 倒下三帧。填上行走里的四个点，看它走起来。",
  "idle": "站立",
  "walk": "行走",
  "die": "倒下",
  "live": "实时",
  "goal_tap": "点按行走里闪烁的点。",
  "goal_walks": "它走起来了！对决马上开始…",
  "goal_ready": "准备好了就点开始。",
  "play": "开始 ▶",
  "another": "换一张草图",
  "name_label": "名字",
  "duel_title": "踩头对决",
  "rival_line": "30 秒内踩对手 3 次",
  "close": "关闭",
  "move_left": "向左",
  "move_right": "向右",
  "jump": "跳",
  "keys_line": "← → / A D 移动 · Space ↑ W 跳 · Esc 关闭 · 手柄：A 跳，B 关闭",
  "hud_you": "你 {n}",
  "hud_rival": "{n} 对手",
  "hud_rule": "踩 3 次 · 30 秒",
  "hud_go": "开始",
  "result_draw": "平局，{a}–{b}。",
  "result_won": "你赢了 {a}–{b}！",
  "result_lost": "对手赢了 {b}–{a}。",
  "moved_in": "{name} 搬进了你的家 · {n}",
  "guest_stays": "{name} 作为客人留下了。",
  "challenge_friend": "向朋友挑战",
  "rematch": "再来一局",
  "draw_another": "再画一个",
  "your_house": "你的家",
  "house_lede": "你完成的每个角色都会搬进来。Pythoneer 的派、宠物和鱼也住在这里。",
  "house_empty": "这里还没人住——先填上上面的四个点。",
  "residents_one": "{n} 位住户",
  "residents_other": "{n} 位住户",
  "guests_one": "{n} 位客人",
  "guests_other": "{n} 位客人",
  "py_counts": "派 {a}/{b} · 宠物 {c}/{d} · 鱼 {e}/{f}",
  "door_sp": "架子、鱼缸和宠物都是空的，等你从 Pythoneer 把它们带来。你的家跟着你走。",
  "visit": "去看看",
  "take_to_app": "带到 App 里",
  "save_png": "将家保存为 Skin PNG",
  "tag_resident": "住户",
  "tag_guest": "客人",
  "btn_duel": "对决",
  "btn_challenge": "挑战",
  "btn_open_app": "在 App 中打开",
  "share_text": "{name} 向你挑战。30 秒内踩它 3 次。",
  "link_copied": "链接已复制",
  "copy_prompt": "复制这个链接",
  "bad_link": "无法读取此链接。请再要一个新的。",
  "privacy": "隐私",
  "privacy_title": "隐私",
  "privacy_p1": "你画的东西和你的家都只留在这个浏览器里，不会上传任何内容。",
  "privacy_p2": "挑战链接把你的角色放在 # 后面。链接的这部分永远不会到达我们的服务器；收到链接的人可以看到这个角色。",
  "privacy_p3": "我们用每次访问新生成的随机数来统计匿名页面事件（例如“开始了一场对决”）。没有 Cookie，没有账户，不保留 IP 地址。",
  "privacy_p4": "Spriteer App 在 App Store 页面上有自己的隐私政策。如有问题：{email}。",
  "not_here": "这里没有。",
  "draw_instead": "去画一个角色 →"
 },
 "zh-Hant": {
  "page_title": "Spriteer — 三格，每個遊戲。",
  "page_title_c": "Spriteer 挑戰",
  "get_app": "取得 App",
  "challenge_default": "一個挑戰",
  "challenge_lede": "在下面畫一個你自己的鬥士——四個點就夠——然後在 30 秒內踩它 3 次。",
  "challenge_name": "{name} 向你挑戰",
  "h1": "三格，每個遊戲。",
  "lede": "每個角色都有站立 · 行走 · 倒下三格。填上行走裡的四個點，看它走起來。",
  "idle": "站立",
  "walk": "行走",
  "die": "倒下",
  "live": "即時",
  "goal_tap": "點一下行走裡閃爍的點。",
  "goal_walks": "它走起來了！對決馬上開始…",
  "goal_ready": "準備好了就點開始。",
  "play": "開始 ▶",
  "another": "換一張草圖",
  "name_label": "名字",
  "duel_title": "踩頭對決",
  "rival_line": "30 秒內踩對手 3 次",
  "close": "關閉",
  "move_left": "向左",
  "move_right": "向右",
  "jump": "跳",
  "keys_line": "← → / A D 移動 · Space ↑ W 跳 · Esc 關閉 · 手把：A 跳，B 關閉",
  "hud_you": "你 {n}",
  "hud_rival": "{n} 對手",
  "hud_rule": "踩 3 次 · 30 秒",
  "hud_go": "開始",
  "result_draw": "平手，{a}–{b}。",
  "result_won": "你贏了 {a}–{b}！",
  "result_lost": "對手贏了 {b}–{a}。",
  "moved_in": "{name} 搬進了你的家 · {n}",
  "guest_stays": "{name} 以客人身分留下了。",
  "challenge_friend": "向朋友挑戰",
  "rematch": "再來一局",
  "draw_another": "再畫一個",
  "your_house": "你的家",
  "house_lede": "你完成的每個角色都會搬進來。Pythoneer 的派、寵物和魚也住在這裡。",
  "house_empty": "這裡還沒有人住——先填上上面的四個點。",
  "residents_one": "{n} 位住戶",
  "residents_other": "{n} 位住戶",
  "guests_one": "{n} 位客人",
  "guests_other": "{n} 位客人",
  "py_counts": "派 {a}/{b} · 寵物 {c}/{d} · 魚 {e}/{f}",
  "door_sp": "架子、魚缸和寵物都是空的，等你從 Pythoneer 把牠們帶來。你的家跟著你走。",
  "visit": "去看看",
  "take_to_app": "帶到 App 裡",
  "save_png": "將家儲存為 Skin PNG",
  "tag_resident": "住戶",
  "tag_guest": "客人",
  "btn_duel": "對決",
  "btn_challenge": "挑戰",
  "btn_open_app": "在 App 中打開",
  "share_text": "{name} 向你挑戰。30 秒內踩它 3 次。",
  "link_copied": "連結已複製",
  "copy_prompt": "複製這個連結",
  "bad_link": "無法讀取此連結。請再要一個新的。",
  "privacy": "隱私權",
  "privacy_title": "隱私權",
  "privacy_p1": "你畫的東西和你的家都只留在這個瀏覽器裡，不會上傳任何內容。",
  "privacy_p2": "挑戰連結把你的角色放在 # 後面。連結的這部分永遠不會傳到我們的伺服器；收到連結的人可以看到這個角色。",
  "privacy_p3": "我們用每次造訪新產生的隨機數來統計匿名頁面事件（例如「開始了一場對決」）。沒有 Cookie，沒有帳號，不保留 IP 位址。",
  "privacy_p4": "Spriteer App 在 App Store 頁面上有自己的隱私權政策。如有問題：{email}。",
  "not_here": "這裡沒有。",
  "draw_instead": "去畫一個角色 →"
 }
};
