#!/usr/bin/env python3
"""Web strings for the 19 UI locales (founder.md §로케일). strings.js is the source of truth.

  strings.py export <strings.js> <out.json>          dump STRINGS as JSON
  strings.py patch  <strings.js> <patch.json>        merge {lang: {key: text}} into STRINGS, validate, write back

Validation: every language's {placeholders} match English for the same key; <b> counts match for *_html keys.
Shared with pythoneer.io/night (same format).
"""
import json, re, sys

def load(path):
    s = open(path).read()
    return json.loads(s[s.index('{'):s.rindex('}') + 1])

def save(path, d):
    head = "// Generated by tools/strings.py (en + 18). Edit through a patch, not by hand.\n"
    open(path, 'w').write(head + 'export const STRINGS = ' + json.dumps(d, ensure_ascii=False, indent=1) + ';\n')

ph = lambda s: sorted(re.findall(r'\{(\w+)\}', s))

def check(d):
    en, bad = d['en'], []
    for l, t in d.items():
        for k, v in t.items():
            base = re.sub(r'_(zero|one|two|few|many)$', '_other', k)
            ref = en.get(k, en.get(base))
            if ref is None: continue
            if ph(v) != ph(ref): bad.append(f'{l}.{k}: {ph(v)} vs {ph(ref)}')
            if k.endswith('_html') and v.count('<b>') != ref.count('<b>'): bad.append(f'{l}.{k}: <b>')
    missing = [f'{l}: {len([k for k in en if k not in t and not k.endswith("_one")])} missing' for l, t in d.items() if any(k not in t for k in en if not k.endswith('_one'))]
    return bad, missing

if __name__ == '__main__':
    cmd, path = sys.argv[1], sys.argv[2]
    d = load(path)
    if cmd == 'export':
        json.dump(d, open(sys.argv[3], 'w'), ensure_ascii=False, indent=1)
    elif cmd == 'patch':
        for l, t in json.load(open(sys.argv[3])).items():
            d.setdefault(l, {}).update(t)
        bad, missing = check(d)
        if bad: sys.exit('refused: ' + '; '.join(bad[:20]))
        save(path, d)
        print('ok', len(d), 'langs', '| missing:', missing or 'none')
